### ISSUE TITLE
How to run the app in docker ? on coreos

### ISSUE THREAD

**Issue by fab5741** [wallix/PEPS#22]
How to run the app without makefile on coreos ? 
I tried to run docker runs command manually, but a container dont want to run, so i think i miss some variables ;

**Comment by hbbio** [comment]
Please read the Makefile, and type the same instructions. There are few variables, so it should be doable. Alternatively, we were waiting for Docker Compose to mature a bit, but it's probably time to use it -- that would be the best way to run on CoreOS.

**Comment by hbbio** [comment]
Update: We are writing alternative build scripts that are compatible with CoreOS.
