### ISSUE TITLE
solr-4.10.4.tgz URL 404

### ISSUE THREAD

**Issue by santium** [wallix/PEPS#67]
When executing `make build`, the task fails due to a 404 on a dependency (solr).

> update-alternatives: using /usr/bin/file-rename to provide /usr/bin/rename (rename) in auto mode
> Processing triggers for libc-bin (2.19-18) ...
> http://www.mirrorservice.org/sites/ftp.apache.org/lucene/solr/4.10.4/solr-4.10.4.tgz:
> 2016-07-04 03:29:16 ERROR 404: Not Found.
> INFO[0105] The command [/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&   apt-get update &&   apt-get -y install lsof curl procps &&   mkdir -p /opt &&   wget -nv --output-document=/opt/$SOLR.tgz http://www.mirrorservice.org/sites/ftp.apache.org/lucene/solr/$SOLR_VERSION/$SOLR.tgz &&   tar -C /opt --extract --file /opt/$SOLR.tgz &&   rm /opt/$SOLR.tgz &&   ln -s /opt/$SOLR /opt/solr] returned a non-zero code: 8 
> Makefile:41: recipe for target 'build' failed
> make: *** [build] Error 1

**Comment by hbbio** [comment]
Latest accepted pull request solves this
